bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top" 

  resources :books, only: [:index, :create, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "/home/about" => "homes#about"
  get "search" => "searches#search"
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :users, through: :favorites
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 200 }, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forword_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backword_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end      
      
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :book_comment, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  attachment :profile_image
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forword_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backword_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    @book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully create!"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book_new = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy!
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully update!"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end

end

bookers2/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

bookers2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully update!"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end


end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_list.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">

     <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, fallback: "no_image.png", size: "60x60" %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
          </tr>
        </table>
        <div class="row">
          <%= link_to ' ', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <% if user == current_user %>
        <% else %>
        </br>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-primary", method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-success", method: :post %>
          <% end %>
        <% end %>

        <h2>New book</h2>
        <%= form_with model: book, local:true do |f| %>

        <label>Title</label><br/>
        <%= f.text_field :title %>
        <br/>
        <label>Opinion</label><br/>
        <%= f.text_area :body %>

        <div>
        <%=f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
   <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0, mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <div class="action">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <dev class="show-back-botton">
        <%= link_to "Show", book_path(@book.id) %>
          |
        <%= link_to "Back", books_path %>
      </dev>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<main>
 <% if @book_new.errors.any? %>
  <%= @book_new.errors.count %>件のerrorが発生しました
  <% @book_new.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
   <% end %>

      <%= render "books/list", book: @book_new, user: @user %>


        <h2>Books</h2>
        <table class="table">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>

          <% @books.each do |book| %>
          <div>
            <tr id="book_<%= book.id %>">
              <th>
                <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.png", size: "40x40" %>
                <% end %>
              </th>
              <th><%= link_to book.title, book_path(book.id) %></th>
              <th><%= book.body %></th>
              <th class="favorite_button">
                <%= render "favorites/favorite", book: book %>
              </th>
              <th>
                <p>コメント数：<%= book.book_comments.count %></p>
              </th>
            </tr>
          </div>
          <% end %>
        </table>
      </div>
    </div>
    </div>

</main>

bookers2/app/views/books/show.html.erb
<%= render "books/list", user: @user, book: @book_new %>

<h2>Book detail</h2>
<table class="table">
  <tr id="book_<%= @book.id %>">
    <th>
      <%= link_to user_path(@book.user.id) do %>
      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.png", size: "40x40" %>
      <br />
      <%= @book.user.name %>
      <% end %>
    </th>
    <th>
      <%= @book.title %>
    </th>
    <th>
      <%= @book.body %>
    </th>
    <th>

    </th>
    <% if @book.user.id == current_user.id %>
    <th><%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success" %></th>
    <th><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger" %></th>
    <% end %>
    <th class="favorite_button">
      <%= render "favorites/favorite", book: @book %>
    </th>
    <th class="comments-count">
      <p>コメント数：<%= @book.book_comments.count%></p>
    </th>
  </tr>
</table>
<table class= "book_comments">
  <%= render "book_comments/index", book: @book %>
</table>
<%= form_with model:[@book,@book_comment], remote: true do |f| %>
  <%= f.text_area :comment, size:"80x7" %><br>
  <%= f.submit '送信'%>
<% end %>

bookers2/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
  </p>
<% else %>
  <p>
    <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
  </p>
<% end %>

bookers2/app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite_button").html("<%= j(render 'favorites/favorite', book: @book) %>");

bookers2/app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite_button").html("<%= j(render 'favorites/favorite', book: @book) %>");

bookers2/app/views/searches/search.html.erb
<h2><%= @range %> search for"<%= params[:word] %>"</h2>

<table class="table">
  <% if @range == "User" %>
    <tbody>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Introduction</th>
      </tr>
      <% if @users.present? %>
        <% @users.each do |user| %>
          <tr>
            <th>
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image, fallback: "no_image.png", size: "40x40" %>
              <% end %>
            </th>
            <th>
              <%= link_to user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </th>
            <th><%= user.introduction %></th>
          </tr>
        <% end %>
      </tbody>
      <% else %>
        <tr>
          <th></th>
          <th>検索結果は存在しません。</th>
          <th></th>
        </tr>
      <% end %>
  <% else %>
    <tbody>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% if @books.present? %>
        <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.png", size: "40x40" %>
              <% end %>
            </th>
            <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </th>
            <th><%= book.body %></th>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <th></th>
          <th>検索結果は存在しません。</th>
          <th></th>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
   <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
      <label for="inputName">Name</label><br/>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label><br/>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <label for="inputProfile">Intoroduction</label><br/>
        <%= f.text_area :introduction, placeholder:"自己紹介" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<%= render "books/list", book: @book, user: current_user %>

<h2>Users</h2>

<table class=table>
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
    <th></th>
    <th></th>
    <th colspan="3"></th>
  </tr>
    <% @users.each do |user| %>
    <tr>
      <th><%= attachment_image_tag user, :profile_image, fallback: "no_image.png", size: "60x60" %></th>
      <th><%= user.name %></th>
      <th>フォロー数：<%= user.followings.count %></th>
      <th>フォロワー数：<%= user.followers.count %></th>
      <th>
        <% if user == current_user %>
        <% else %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        <% end %>
     </th>
     <th><%= link_to "Show", user_path(user.id) %></th>
  </tr>
  <% end %>
</table>
</div>
</div>

bookers2/app/views/users/show.html.erb
<%= render "books/list", book: @book, user: @user %>

<h2>Books</h2>
        <table class="table">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>

          <% @books.each do |book| %>
          <div>
            <tr>
              <th>
                <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag @user, :profile_image, fallback: "no_image.png", size: "40x40" %>
                <% end %>
                </th>
              <th><%= link_to book.title, book_path(book.id) %></th>
              <th><%= book.body %></th>
              <th><p>コメント数：<%= book.book_comments.count%></p></th>
            </tr>
          </div>
          <% end %>
        </table>
        </div>
        </div>